default_platform(:ios)

platform :ios do
  desc "Deploy to TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: false
    )

    get_provisioning_profile(
      api_key: api_key,
      app_identifier: "com.technoetic.HealthBotWatch.ios",
      adhoc: false,
      force: true
    )
    appstore_uuid = lane_context[SharedValues::SIGH_UUID]

    update_project_provisioning(
      xcodeproj: "HealthBotWatch.xcodeproj",
      profile: lane_context[SharedValues::SIGH_PROFILE_PATH],
      target_filter: "HealthBotWatch",
      build_configuration: "Release"
    )

    increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M"),
      xcodeproj: "HealthBotWatch.xcodeproj"
    )

    build_app(
      scheme: "HealthBotWatch",
      project: "HealthBotWatch.xcodeproj",
      configuration: "Release",
      destination: "generic/platform=iOS",
      export_method: "app-store",
      export_options: {
        teamID: ENV["TEAM_ID"],
        uploadSymbols: true,
        compileBitcode: false,
        thinning: "<none>",
        signingStyle: "manual",
        provisioningProfiles: {
          "com.technoetic.HealthBotWatch.ios" => appstore_uuid,
        },
        signingCertificate: "iPhone Distribution"
      },
      xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='iPhone Distribution' ENABLE_BITCODE=NO",
      clean: true
    )

    upload_to_testflight(
      api_key: api_key,
      app_identifier: "com.technoetic.HealthBotWatch.ios",
      skip_waiting_for_build_processing: true,
      skip_submission: true
    )
  end

  desc "Ad Hoc build for USB install"
  lane :adhoc do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_PRIVATE_KEY"],
      is_key_content_base64: false
    )

    register_devices(
      devices: {
        "iPhone SE" => "00008110-001C31622647801E",
        "Apple Watch Series 7" => "00008301-D890D9843E8B402E"
      },
      api_key: api_key
    )

    # iOS Ad Hoc profile
    get_provisioning_profile(
      api_key: api_key,
      app_identifier: "com.technoetic.HealthBotWatch.ios",
      adhoc: true,
      force: true
    )
    ios_uuid = lane_context[SharedValues::SIGH_UUID]

    update_project_provisioning(
      xcodeproj: "HealthBotWatch.xcodeproj",
      profile: lane_context[SharedValues::SIGH_PROFILE_PATH],
      target_filter: "HealthBotWatch",
      build_configuration: "Release"
    )

    increment_build_number(
      build_number: Time.now.strftime("%Y%m%d%H%M"),
      xcodeproj: "HealthBotWatch.xcodeproj"
    )

    build_app(
      scheme: "HealthBotWatch",
      project: "HealthBotWatch.xcodeproj",
      configuration: "Release",
      destination: "generic/platform=iOS",
      export_method: "ad-hoc",
      export_options: {
        teamID: ENV["TEAM_ID"],
        compileBitcode: false,
        thinning: "<none>",
        signingStyle: "manual",
        provisioningProfiles: {
          "com.technoetic.HealthBotWatch.ios" => ios_uuid,
        },
        signingCertificate: "iPhone Distribution"
      },
      xcargs: "CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY='iPhone Distribution' ENABLE_BITCODE=NO",
      clean: true
    )
  end
end
